import streamlit as st
from groq import Groq
from fpdf import FPDF
import datetime

# --- 1. DARK MODE & UI OVERHAUL (Grok Layout) ---
st.set_page_config(page_title="Wassool AI", page_icon="⚖️", layout="centered")

# Custom CSS for the Black/Gold/Dark Grey "Grok" aesthetic
st.markdown("""
    <style>
    .main {
        background-color: #000000;
    }
    .stApp {
        background-color: #000000;
        color: #ffffff;
    }
    /* Input fields */
    .stTextInput>div>div>input, .stSelectbox>div>div>select, .stTextArea>div>div>textarea {
        background-color: #1a1a1a !important;
        color: #ffffff !important;
        border: 1px solid #333 !important;
    }
    /* Buttons */
    .stButton>button {
        width: 100%;
        background-color: #ffffff !important;
        color: #000000 !important;
        font-weight: bold;
        border-radius: 5px;
        border: none;
        padding: 10px;
    }
    .stButton>button:hover {
        background-color: #d4af37 !important; /* Gold hover */
    }
    /* Titles */
    h1, h2, h3 {
        color: #ffffff !important;
        font-family: 'Space Grotesk', sans-serif;
    }
    /* Sidebar/Divider */
    hr { border-top: 1px solid #333 !important; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. CONFIGURATION (Groq API) ---
try:
    GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
except:
    st.error("⚠️ GROQ_API_KEY not found in Streamlit Secrets.")
    st.stop()

client = Groq(api_key=GROQ_API_KEY)

# --- 3. DATABASE ---
nodal_officers = {
    "IndiGo": "nodal@goindigo.in",
    "Zomato": "grievance@zomato.com",
    "HDFC Bank": "grievance.redressal@hdfcbank.com",
    "Amazon": "grievance-officer@amazon.in",
    "Flipkart": "grievance.officer@flipkart.com"
}

# --- 4. THE APP UI ---
st.title("⚖️ WASSOOL AI")
st.markdown("#### *The Consumer Fighter Engine*")
st.write("Professional Legal Notices generated by high-speed inference.")
st.divider()

# Simplified Input Layout
col1, col2 = st.columns(2)
with col1:
    user_name = st.text_input("YOUR NAME")
    issue_type = st.selectbox("ISSUE CATEGORY", 
        ["Refund Denied", "Defective Product", "Service Failure", "Security Deposit", "Hidden Charges"])

with col2:
    company_name = st.text_input("COMPANY NAME")
    amount = st.number_input("AMOUNT (₹)", min_value=0, step=500)

details = st.text_area("CASE DETAILS", placeholder="Explain exactly what happened...")

st.write("") # Spacer
if st.button("EXECUTE LEGAL DRAFT"):
    if user_name and company_name and details:
        with st.spinner("Processing through Groq-LLaMA-3..."):
            
            # --- 5. THE AI LOGIC (Groq Inference) ---
            prompt = f"""
            System: You are an elite Indian Consumer Rights Advocate.
            Task: Draft a formal 'Demand Notice' from {user_name} to {company_name}.
            
            Details:
            - Category: {issue_type}
            - Recovery Amount: ₹{amount}
            - Incident: {details}
            - Notice Date: {datetime.date.today()}
            
            Legal Requirements:
            1. Cite: Consumer Protection Act 2019 (specifically Section 35).
            2. For Flights: Cite DGCA CAR Section 3, Series M.
            3. Tone: Highly professional, sharp, and non-negotiable.
            4. Deadline: 7 days for resolution before legal filing with NCH/Consumer Forum.
            5. Output only the notice. No conversational text.
            """
            
            chat_completion = client.chat.completions.create(
                messages=[{"role": "user", "content": prompt}],
                model="llama-3.3-70b-versatile", # High speed/High intelligence
                temperature=0.5
            )
            
            notice_text = chat_completion.choices[0].message.content
            
            # Display Result
            st.divider()
            st.subheader("GENERATED DRAFT")
            st.text_area("", notice_text, height=400)
            
            # --- 6. PDF GENERATION ---
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", size=11)
            pdf.set_text_color(0, 0, 0) # Black text for printing
            
            pdf.set_font("Arial", 'B', 16)
            pdf.cell(0, 10, "FORMAL LEGAL NOTICE", ln=True, align='C')
            pdf.ln(10)
            
            pdf.set_font("Arial", size=11)
            # PDF doesn't like special symbols, cleaning...
            clean_text = notice_text.encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 7, clean_text)
            
            pdf_bytes = pdf.output(dest='S').encode('latin-1')
            
            st.download_button(
                label="📥 DOWNLOAD LEGAL PDF",
                data=pdf_bytes,
                file_name=f"Wassool_Notice_{company_name}.pdf",
                mime="application/pdf"
            )

            # --- 7. THE NODAL LOCK ---
            if company_name in nodal_officers:
                st.warning(f"🔒 Nodal Officer for {company_name} identified.")
                st.info(f"Support emails are often ignored. Pay to unlock the legal Nodal Email for {company_name}.")
    else:
        st.warning("Please fill in all details before executing.")

st.divider()
st.caption("Powered by Llama-3-70b via Groq | Built for Consumer Justice")
